apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resilient-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timothydevQ/resilient-platform
    targetRevision: main
    path: infrastructure/kubernetes/services
  destination:
    server: https://kubernetes.default.svc
    namespace: resilient-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
# app
